plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

dependencies {
    implementation project(':common')
    implementation 'com.github.mikhalexandr:programming-lab8-gui:1.1.7'
    implementation 'org.slf4j:slf4j-api:2.0.13'
    implementation 'ch.qos.logback:logback-classic:1.5.25'
    implementation 'ch.qos.logback:logback-core:1.5.25'
}

javafx {
    version = '21.0.4'
    modules = ['javafx.controls']
}

application {
    mainClass = 'dev.mikhalexandr.client.app.Launcher'
    applicationDefaultJvmArgs = [
        '--enable-native-access=ALL-UNNAMED',
        '--sun-misc-unsafe-memory-access=allow'
    ]
}

tasks.named('run') {
    dependsOn check
}

tasks.register('jarWithDeps', Jar) {
    archiveClassifier = 'jar-with-dependencies'
    manifest { attributes 'Main-Class': application.mainClass }
    from sourceSets.main.output
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
    eachFile { details ->
        if (details.path.startsWith('META-INF/') && details.name ==~ /.*\.(SF|RSA|DSA|EC)/) {
            details.exclude()
        }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('jarWithDeps') {
    dependsOn check
}
