plugins {
    id 'application'
}

dependencies {
    implementation project(':common')
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'ch.qos.logback:logback-classic:1.5.25'
    implementation 'ch.qos.logback:logback-core:1.5.25'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.84'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.84'
    implementation 'org.postgresql:postgresql:42.7.7'
    implementation 'org.jooq:jooq:3.19.15'
    implementation 'redis.clients:jedis:5.1.0'
    implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.2'
}

application {
    mainClass = 'dev.mikhalexandr.server.Server'
}

tasks.named('run') {
    dependsOn check
}

tasks.register('jarWithDeps', Jar) {
    archiveClassifier = 'jar-with-dependencies'
    manifest { attributes 'Main-Class': application.mainClass }
    from sourceSets.main.output
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
    eachFile { details ->
        if (details.path.startsWith('META-INF/') && details.name ==~ /.*\.(SF|RSA|DSA|EC)/) {
            details.exclude()
        }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('jarWithDeps') {
    dependsOn check
}
