name: Bump Submodule Pointer

on:
  push:
    branches:
      - main

jobs:
  bump-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repository
        uses: actions/checkout@v4
        with:
          repository: mikhalexandr/itmo-cse-programming
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Bump submodule pointer
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git submodule update --remote lab5-8

          if [[ -n $(git status -s) ]]; then
            git add lab5-8
            git commit -m "chore(lab5-8): bump submodule pointer"
            git push
            echo "Success: Parent repository bumped!"
          else
            echo "No changes needed."
          fi
